#!/bin/sh

BLUE="\033[1;34m"
NEUT="\033[0m"

printf "$BLUE
This is the same as the last (they're all the same) but we have to turn on aslr
$NEUT 
../../aslr.sh on"
read
../../aslr.sh on


printf "$BLUE
Because aslr doesen't scramble the addresses in the .text (the code) section we can use the same exploit
We will see slightly harder version in the next level with PIE where these addresses ARE scrambled
$NEUT
../../level1/easy/sol/exploit.py"
read
../../level1/easy/sol/exploit.py
